# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
        . /etc/bashrc
fi

# User specific aliases and functions
export PS1='\u@\H:\w>'

export LD_POINTER_GUARD=0

# Setup sybase-related environment
. {{ installation_path }}/sybase/SYBASE.sh
