---
# This playbook deploys logstash agents

- hosts: logstash
  user: root

  vars_files:
    - "vars/base.yml"
    - "vars/{{ hostfile }}"
    - "vars/logstash_{{ env }}.yml"

  roles:
  - logstash-shipper
