---
# This playbook deploys logstash (indexer and web)

- hosts: logserver_indexer
  user: root

  vars_files:
    - "vars/base.yml"
    - "vars/logstash_{{ env }}.yml"
    - "vars/elasticsearch_{{ env }}.yml"

  roles:
  - logstash-indexer
  - logstash-web
